# Generated by Django 3.1.4 on 2022-06-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220627_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_post',
            new_name='date_posted',
        ),
    ]
